### ISSUE TITLE
Error running bootstrap script

### ISSUE THREAD

**Issue by KRUBERLICK** [TextureGroup/Weaver#1]
Hi, I`m getting an error when executing bootstrap script:

```
Macs-MacBook-Pro:ponyd KRUBERLICK$ curl -s https://raw.githubusercontent.com/TextureGroup/Weaver/master/scripts/bootstrap-ponyd.py | python - --never-download ~/Library/Weaver
New python executable in /Users/KRUBERLICK/Library/Weaver/bin/python
Cannot find a wheel for setuptools
Cannot find a wheel for pip
Installing setuptools, pip, wheel...
  Complete output from command /Users/KRUBERLICK/Library/Weaver/bin/python - setuptools pip wheel:
  Collecting setuptools
  Could not find a version that satisfies the requirement setuptools (from versions: )
No matching distribution found for setuptools
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "<stdin>", line 2360, in <module>
  File "<stdin>", line 715, in main
  File "<stdin>", line 947, in create_environment
  File "<stdin>", line 903, in install_wheel
  File "<stdin>", line 799, in call_subprocess
OSError: Command /Users/KRUBERLICK/Library/Weaver/bin/python - setuptools pip wheel failed with error code 1
```

**Comment by smoothdvd** [comment]
me too

**Comment by nguyenhuy** [comment]
Oh hey, I heard reinstall "virtualenv" helps: https://stackoverflow.com/questions/10544067/why-cant-virtualenv-find-pkg-resources - https://asyncdisplaykit.slack.com/archives/C6115969W/p1499226853468256?thread_ts=1499136444.312924&cid=C6115969W

**Comment by smoothdvd** [comment]
@nguyenhuy Finally, I installed it manually.
First run bootstrap script with no-pip, no-setuptools, no-wheel option;
then active virtualenv and install pip with python get-pip.py;
and step by step with weaver document to compile ponyd.

**Comment by nguyenhuy** [comment]
That's great to know. If you can come up with a better installation guide, please fire up a PR. Thank you!

@KRUBERLICK Please try the steps above and let us know if it works!

**Comment by KRUBERLICK** [comment]
@nguyenhuy reinstalling `virtualenv` helped, thanks!

**Comment by nguyenhuy** [comment]
Awesome. Enjoy!

**Comment by camuscodemic** [comment]
@nguyenhuy reinstalling actually work. Thanks!

If you manage python at anaconda then you will meet serious installation problem on Weaver with virtualenv like i did, it messed up the system path of accessing py library like ssl.py. My solution was making sure i m installing Weaver using system python. 

After complete installation, you can resume conda management.

ref:
https://stackoverflow.com/questions/38221144/how-to-solve-the-issue-of-the-conflict-of-anaconda-and-virtualenv

**Comment by nguyenhuy** [comment]
Awesome, @MiguelChiang. And thank you for letting me know!
