### ISSUE TITLE
cannot install dependencies

### ISSUE THREAD

**Issue by cuong1112035** [TextureGroup/Weaver#2]
I cannot install dependencies at step 4. Terminal said that "No such file or directory"
<img width="549" alt="screen shot 2017-08-07 at 10 25 32 am" src="https://user-images.githubusercontent.com/6124016/29011126-c7910434-7b5a-11e7-8b76-0b4245de5cb3.png">

**Comment by nguyenhuy** [comment]
Hi, please make sure you have "pip" properly installed before running the 1st step. Also double check that you have python 2.7 and virtualenv.

**Comment by nguyenhuy** [comment]
This may also help: https://apple.stackexchange.com/questions/142752/broke-my-python-easy-install-how-to-fix
